### ISSUE TITLE
Someone stile my 12 letter words from this spp

### ISSUE THREAD

**Issue by jmlarkin** [bykovme/nswallet#43]
I got 26,000 stolen from wallet I don't have the words any where except on this app.

Joy Larkin

**Comment by bykovme** [comment]
The app stores the data encrypted with AES-256 locally on your device, the only way somebody could get access to your data inside the app is to get full control of your device and get your master password which is highly unlikely (unless you have shared your master password AND the device (or the data backup) with somebody.

**Comment by jmlarkin** [comment]
You app ruined my life they somehow got into my app stole all my 200 password went into all my crypto wallets and stole all the money wiped them dry. I lost 100,000.00 dollars in crypto money.They put Webcam software on our router and stole my identity to create exchange accounts to trade the list goes on they stole my files from my computer I gave silver they took gold. They put forwarding email address on my email account and monitored my emails then went in for the kill. Identity thief to the highest degree.

Change the way your app works because if I had this happen to me others will to.

Please investigate who got into my account on ***@***.*** 

Thank you for your prompt attention in this matter.

Joy Larkjn


----- Original Message -----
