### ISSUE TITLE
Failed to create backup file on some droid devices

### ISSUE THREAD

**Issue by bykovme** [bykovme/nswallet#7]
Users reported that they are not able to create new backup files on some Android phones (mostly latest Samsungs)

**Comment by Jano233** [comment]
I've got the same problem with a Pocophone F1.
I tried to uninstall NS Wallet and reinstall it, without any success. After reinstalling the app, it asked me for my current password and I'm not able to create new archive.

**Comment by alpinefarmer1** [comment]
I have the same problem here with a Galaxy S10. I was able to do the backup on my old phone and send it to the new phone and put it in the proper file but the app on the new phone does not recognize the backup file
![20200314_201741](https://user-images.githubusercontent.com/62003859/76694701-69a4e180-6633-11ea-9c90-49c2ccfec851.jpg)
![20200314_201648](https://user-images.githubusercontent.com/62003859/76694704-73c6e000-6633-11ea-9e35-8a7cc045d9c0.jpg)

**Comment by ilyalehchylin** [comment]
@Jano233, @alpinefarmer1, 
Please try the new **beta** version **4.05.2093**. 
To become a beta-tester, you can use **[this link](https://play.google.com/apps/testing/com.nyxbull.nswallet)**.

**Comment by Jano233** [comment]
Even with beta version, it doesn't change anything.
I'm not able to do any backup and when I put a back up file in the appropriate NSW folder, It seems not to be seen by the app (as if the folder was empty).

**Comment by dlk7** [comment]
When will this issue with backups be resolved? Backup used to work in prior version. Is there anyway to roll back to version woth backup capacity?

**Comment by bykovme** [comment]
The issue is happening only on the new devices (Android 10), as Google changed the approach of work with external storage, in a few words, it is not existing anymore, now storage is used the same way as on Apple devices, working with files is fully sandboxed, all external storage functions are deprecated.
I will move the backup folder into internal app storage, that should fix the issue. Fixed app will be available on the BETA channel tomorrow.

**Comment by Jano233** [comment]
It's working perfectly now.
The app is able to create back-up file again.
Thank you very much for your help.

**Comment by ilyalehchylin** [comment]
Glad to hear that. Thanks for your feedback!

**Comment by alpinefarmer1** [comment]
Where in "device memory" should the backed up file be moved so its recognized by app.

**Comment by Jano233** [comment]
On my phone, the backup folder is there : internal storage/Android/data/com.nyxbull.nswallet/files/nswBackup/

**Comment by dlk7** [comment]
Im not sure about yhis process...as i really need to dig around in my phone files.  All i get from app now is a message box after i tap the database icon in the corner that a backup was created. Previously the app listed the files after creation. This is more than what was previously needed to use the app.

**Comment by bykovme** [comment]
> Im not sure about yhis process...as i really need to dig around in my phone files. All i get from app now is a message box after i tap the database icon in the corner that a backup was created. Previously the app listed the files after creation. This is more than what was previously needed to use the app.

Please, use the app with version 4.07+, looks like you are still using older version with issue.

**Comment by dlk7** [comment]
Thanks for the response. I hv updated my app on my phone. However, the date of release is 3.3020 and i had auto update on for my phone. So, i have my concern about the accuracy of the claim that the issue was only happening on new phones. I will moniter going forward.On Mar 30, 2020 9:31 AM, Alex Bykov <notifications@github.com> wrote:

Im not sure about yhis process...as i really need to dig around in my phone files. All i get from app now is a message box after i tap the database icon in the corner that a backup was created. Previously the app listed the files after creation. This is more than what was previously needed to use the app.

Please, use the app with version 4.07+, looks like you are still using older version with issue.
